### ISSUE TITLE
Move Navbar above header

### ISSUE THREAD

**Issue by Sujal-2820** [Sujal-2820/Hacktoberfest-Web#1]
I want the navbar to appear above the header where "Sample Website" is written.

Any other changes to the navbar which would enhance its appearance is highly appreciated!!

**Comment by aryankshl** [comment]
hey @Sujal-2820 can you please assign this to me?

**Comment by Sujal-2820** [comment]
@aryankshl go for it. 

Make sure to provide a snip of the changes after making the changes in your local system.

Any other enhancement in Navbar from your end will be highly appreciated.

All the Best!!

**Comment by akshitjain2004** [comment]
@Sujal-2820  is this issue resolved ?.
If not please assign it to me. I'll do it

**Comment by akshitjain2004** [comment]
Navbar above the div
![Screenshot 2023-10-14 132011](https://github.com/Sujal-2820/Hacktoberfest-Web/assets/94056853/7d4c4a27-8614-42e7-a83f-808afc2ea384)
Added hover effect
![image](https://github.com/Sujal-2820/Hacktoberfest-Web/assets/94056853/49330605-86e1-4a78-b723-2a51e3db53ff)

**Comment by Sujal-2820** [comment]
Awesome @akshitjain2004.
I would assign this issue to you.

Make sure to add a proper explanation of your changes along with the Screenshot in your PR

**Comment by akshitjain2004** [comment]
@Sujal-2820  Please review the PR. 

How can I get it accepted in hacktober fest? Lemme know what should I do ?
![image](https://github.com/Sujal-2820/Hacktoberfest-Web/assets/94056853/0bebd84f-78af-432e-9901-9017d611de8b)

**Comment by Sujal-2820** [comment]
Hey @akshitjain2004,
I have merged your PR into the main branch.
You have done a phenomenal work 🙂

You might have got a mail regarding the same...

Additionally, You can check the hacktoberfest website. There it would reflect that your PR has been accepted.

**Comment by akshitjain2004** [comment]
Yes! This is my first PR. Thank you. 
You may close the issue now!

**Comment by Sujal-2820** [comment]
Awesome 👍
