### ISSUE TITLE
Changing the heading color

### ISSUE THREAD

**Issue by YuktaG123** [Sujal-2820/Hacktoberfest-Web#6]
Hey @Sujal-2820 ,

I would like to change the heading colors of the headings such as: Images , Collage Reviews and Study Material.

Can you please assign this issue to me and label it as "Hacktoberfest-accepted"

**Comment by Sujal-2820** [comment]
Sure @YuktaG123,
Go for it 💯
You can also add some Hover effects to it in order to make it look Good!!

Make sure add screenshots of your work in the Description of your PR

**Comment by sai-kumar0** [comment]
Hey @Sujal-2820 ,

I would like to remove the empty space under the footer and update the footer and elements in it. I will make it look good like footer in every other modern website.

Could you please assign this to me and label it as "Hacktoberfest-accepted"

**Comment by Sujal-2820** [comment]
Sure @sai-kumar0, I'll assign this issue to you. 🙂

But please make a new Issue, so that I can assign this to you separately
