### ISSUE TITLE
Feature : Adding login and signup page

### ISSUE THREAD

**Issue by yube01** [Sujal-2820/Hacktoberfest-Web#8]
Simple dummy login and register page could be added in this page when user click on sign in or sign up button

**Comment by Sujal-2820** [comment]
That's awesome @yube01 😄

I'll assign the issue to you but do remember to add a proper description of your PR.

You could be asked to deploy your forked repository on GitHub pages and then send the link of the same. So that, it would be easier for be to view the changes.

All the Best 👍
